baseURL = "https://barsegyan.me"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Artur Barsegyan"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-165432214-1"

[params]
title = "I'm Artur Barsegyan"
author = "Artur Barsegyan"
description = "Product Manager of Tarantool/Mail.Ru"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/artur-barsegyan"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:a.barsegyan96@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Portfolio"
  identifier = "home"
  weight = 300
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 300
  identifier = "posts"
  url = "/post/"

